version: "3"
services:
  ros2_click_teleop:
    build: .
    container_name: ros2_click_teleop
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/video0:/dev/video0
    stdin_open: true
    tty: true

